"""create reels model

Revision ID: b50da8f9f81c
Revises: 4619bc2801bc
Create Date: 2026-01-29 19:13:57.630862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50da8f9f81c'
down_revision: Union[str, Sequence[str], None] = '4619bc2801bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeditems',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feed_items')
    op.add_column('reels', sa.Column('video_path', sa.String(), nullable=False))
    op.add_column('reels', sa.Column('duration', sa.Float(), nullable=False))
    op.add_column('reels', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('reels', 'caption')
    op.drop_column('reels', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reels', sa.Column('video_url', sa.VARCHAR(), nullable=False))
    op.add_column('reels', sa.Column('caption', sa.VARCHAR(), nullable=False))
    op.drop_column('reels', 'updated_at')
    op.drop_column('reels', 'duration')
    op.drop_column('reels', 'video_path')
    op.create_table('feed_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feeditems')
    # ### end Alembic commands ###
