"""create like and comment models

Revision ID: fa78ca5b8f3f
Revises: ddb0b5f4a9af
Create Date: 2026-01-30 17:30:00.582435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa78ca5b8f3f'
down_revision: Union[str, Sequence[str], None] = 'ddb0b5f4a9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create tables only if they don't exist
    if 'reelcomments' not in existing_tables:
        op.create_table('reelcomments',
        sa.Column('reel_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'reellikes' not in existing_tables:
        op.create_table('reellikes',
        sa.Column('reel_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Check if columns already exist before adding them
    if 'reels' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('reels')]
        if 'views_count' not in existing_columns:
            op.add_column('reels', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))
        if 'likes_count' not in existing_columns:
            op.add_column('reels', sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))
        if 'comments_count' not in existing_columns:
            op.add_column('reels', sa.Column('comments_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reels', 'comments_count')
    op.drop_column('reels', 'likes_count')
    op.drop_column('reels', 'views_count')
    op.drop_table('reellikes')
    op.drop_table('reelcomments')
    # ### end Alembic commands ###
